baseURL = 'https://henrysky.github.io/'
languageCode = 'en-us'
enableGitInfo = true

[params]
  description = 'Personal Website of Henry W. Leung'
  email = 'henrysky [dot] leung [at] utoronto [dot] ca'
  startyears = '2018'
  themecolor = '003366'

[frontmatter]
  date = ["lastmod", "date", "publishDate"]
  lastmod = ["publishDate", ":git", "lastmod", "date"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
        codeFences = true
        guessSyntax = true
        hl_Lines = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4
        noClasses = false
        style = "monokai"
        pygmentsUseClasses = true
        pygmentsCodefences = true

[languages]
  [languages.en]
    languageCode = "en-CA"
    languageName = "English"
    title = '''Henry Leung's Personal Website'''
    [languages.en.params]
      authors = 'Henry W. Leung'
      navbar_shortdesc = 'Astronomer & Data Scientist'
      lastupdate = 'Last Updated'
      copyright = 'Copyrighted'
  [languages.zh]
    languageCode = "zh-yue"
    languageName = "Cantonese"
    title = 'Henry Leung 嘅個人網站'
    [languages.zh.params]
      authors = '梁瑋軒'
      navbar_shortdesc = '天文學 & 數據科學家'
      lastupdate = '最後更新'
      copyright = '版權所有'
