name: build and deploy to github pages

on:
  push:
    branches: [ master ]  # Set a branch that will trigger a deployment
  schedule:
    # Runs at 13:00 UTC (08:00 Toronto?) on every Monday because ADS update on every weekend
    - cron: '0 13 * * 1'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install numpy pandas requests
      - name: Build Bootstrap CSS
        run: | 
          npm i bootstrap autoprefixer upath sass shelljs 
          node src/build-scss.js
          node src/build-scripts.js
          node src/build-assets.js
      - name: Build list of publication
        run: ADS_TOKEN=${{ secrets.ADS_TOKEN }} python ./src/gen_pub_list.py 
      - name: Build Hugo site
        run: hugo
      - name: Download my CV artifact
        run: |
          python ./src/download_CV.py --token ${{ secrets.GH_TOKEN }}
          unzip -qq CV_PDFs.zip -d CV_PDFs
          mkdir ./public/assets/cvpdf/
          cp CV_PDFs/CV_Full.pdf ./public/assets/cvpdf/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --base ./public/ --verbose --no-progress './public/**/*.html' --max-concurrency 1
          format: markdown
          output: /tmp/result.md
          token: ${{ secrets.GH_TOKEN }}
          fail: true