name: build and deploy to github pages

on:
  push:
    branches: [ master ]  # Set a branch that will trigger a deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install numpy pandas requests
      - name: Build Bootstrap CSS
        run: | 
          npm i bootstrap@5.3.0-alpha1 autoprefixer upath sass shelljs 
          node src/build-scss.js
      - name: Build list of publication
        run: ADS_TOKEN=${{ secrets.ADS_TOKEN }} python ./src/gen_pub_list.py 
      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/hugo'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public